/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javacal.calculator_java;

import java.awt.event.KeyEvent;


/**
 *
 * @author Suzaku
 */
public class UIjavaCalc extends javax.swing.JFrame {

    /**
     * Creates new form UIjavaCalc
     */
    public UIjavaCalc() {
        initComponents();
    }

    int num,ans,perhitungan;
    double x,sin,conv;
    
    public void aritmatika()
    {
        switch(perhitungan)
        {
            case 1 : //tambah
                ans = num + Integer.parseInt(textField1.getText());
                textField1.setText(Integer.toString(ans));
                break;
            case 2 : // kurang
                ans = num - Integer.parseInt(textField1.getText());
                textField1.setText(Integer.toString(ans));
                break;
            case 3 : // kali
                ans = num * Integer.parseInt(textField1.getText());
                textField1.setText(Integer.toString(ans));
                break;
            case 4 : //bagi
                ans = num / Integer.parseInt(textField1.getText());
                textField1.setText(Integer.toString(ans));
                break;
           
          
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultField = new javax.swing.JTextField();
        textField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        backspaceButton = new javax.swing.JButton();
        minButton = new javax.swing.JButton();
        rootButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        resButton = new javax.swing.JButton();
        plsminButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        logButton = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        sinhButton = new javax.swing.JButton();
        phiButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        coshButton = new javax.swing.JButton();
        xyButton = new javax.swing.JButton();
        tanButtton = new javax.swing.JButton();
        tanhButton = new javax.swing.JButton();
        x2Button = new javax.swing.JButton();
        cbrButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        x3Button = new javax.swing.JButton();
        bryButton = new javax.swing.JButton();
        hexButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultField.setText("0");
        resultField.setEnabled(false);
        resultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFieldActionPerformed(evt);
            }
        });

        textField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textField1.setText("0");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backspaceButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backspaceButton.setText("B");
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        minButton.setText("-");
        minButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minButtonActionPerformed(evt);
            }
        });

        rootButton.setText("√");
        rootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearButton.setText("C");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        resButton.setText("=");
        resButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resButtonActionPerformed(evt);
            }
        });

        plsminButton.setText("±");
        plsminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plsminButtonActionPerformed(evt);
            }
        });

        commaButton.setText(".");
        commaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaButtonActionPerformed(evt);
            }
        });

        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        divideButton.setText("/");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backspaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rootButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sevenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eightButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nineButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sixButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplyButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(zeroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plsminButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(oneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(threeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divideButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backspaceButton)
                    .addComponent(minButton)
                    .addComponent(rootButton)
                    .addComponent(ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenButton)
                    .addComponent(plusButton)
                    .addComponent(nineButton)
                    .addComponent(eightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourButton)
                    .addComponent(multiplyButton)
                    .addComponent(sixButton)
                    .addComponent(fiveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneButton)
                    .addComponent(divideButton)
                    .addComponent(threeButton)
                    .addComponent(twoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroButton)
                    .addComponent(resButton)
                    .addComponent(plsminButton)
                    .addComponent(commaButton)))
        );

        logButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logButton.setText("Log");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        sinButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sinButton.setText("Sin");
        sinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinButtonActionPerformed(evt);
            }
        });

        sinhButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sinhButton.setText("Sinh");
        sinhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhButtonActionPerformed(evt);
            }
        });

        phiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phiButton.setText("Phi");
        phiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phiButtonActionPerformed(evt);
            }
        });

        cosButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cosButton.setText("Cos");
        cosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosButtonActionPerformed(evt);
            }
        });

        coshButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        coshButton.setText("Cosh");
        coshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshButtonActionPerformed(evt);
            }
        });

        xyButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xyButton.setText("X^Y");
        xyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyButtonActionPerformed(evt);
            }
        });

        tanButtton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tanButtton.setText("Tan");
        tanButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanButttonActionPerformed(evt);
            }
        });

        tanhButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tanhButton.setText("Tanh");
        tanhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhButtonActionPerformed(evt);
            }
        });

        x2Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        x2Button.setText("X^2");
        x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ButtonActionPerformed(evt);
            }
        });

        cbrButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbrButton.setText("Cbr");
        cbrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrButtonActionPerformed(evt);
            }
        });

        runButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        x3Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        x3Button.setText("X^3");
        x3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x3ButtonActionPerformed(evt);
            }
        });

        bryButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bryButton.setText("Bry");
        bryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bryButtonActionPerformed(evt);
            }
        });

        hexButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hexButton.setText("Hex");
        hexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(logButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sinButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sinhButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(phiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coshButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(xyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanButtton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanhButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(x2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbrButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(x3Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hexButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logButton)
                    .addComponent(sinButton)
                    .addComponent(sinhButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phiButton)
                    .addComponent(cosButton)
                    .addComponent(coshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xyButton)
                    .addComponent(tanButtton)
                    .addComponent(tanhButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x2Button)
                    .addComponent(cbrButton)
                    .addComponent(runButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x3Button)
                    .addComponent(bryButton)
                    .addComponent(hexButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultFieldActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        int length = textField1.getText().length();
        int number = textField1.getText().length() -1;
        
        String store;
        
        if (length > 0)
        {
            StringBuilder back = new StringBuilder(textField1.getText());
            back.deleteCharAt(number);
            store = back.toString();
            textField1.setText(store);
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void minButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minButtonActionPerformed
       num = Integer.parseInt(textField1.getText());
       perhitungan=2;
       textField1.setText("");
       resultField.setText(num + "-"); 
    }//GEN-LAST:event_minButtonActionPerformed

    private void rootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootButtonActionPerformed
         x = Double.valueOf(textField1.getText());
            sin =Math.sqrt(Math.toRadians(x));
            textField1.setText(""+sin);
            resultField.setText("√"+x);
    }//GEN-LAST:event_rootButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        resultField.setText("");
        textField1.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
      num = Integer.parseInt(textField1.getText());
       perhitungan=1;
       textField1.setText("");
       resultField.setText(num + "+"); 
    }//GEN-LAST:event_plusButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
       textField1.setText(textField1.getText() + "9");
    }//GEN-LAST:event_nineButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        textField1.setText(textField1.getText() + "8");
    }//GEN-LAST:event_eightButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        textField1.setText(textField1.getText() + "7");
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
       num = Integer.parseInt(textField1.getText());
       perhitungan=3;
       textField1.setText("");
       resultField.setText(num + "*"); 
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        textField1.setText(textField1.getText() + "6");
    }//GEN-LAST:event_sixButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        textField1.setText(textField1.getText() + "5");
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        textField1.setText(textField1.getText() + "4");
    }//GEN-LAST:event_fourButtonActionPerformed

    private void resButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resButtonActionPerformed
       aritmatika();
       resultField.setText("");
    }//GEN-LAST:event_resButtonActionPerformed

    private void plsminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plsminButtonActionPerformed
              x = Double.parseDouble(String.valueOf(textField1.getText()));
              sin = x * -1;        
            textField1.setText(""+sin);
            resultField.setText(""+x);
    }//GEN-LAST:event_plsminButtonActionPerformed

    private void commaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaButtonActionPerformed
    textField1.setText(textField1.getText() + ".");
    }//GEN-LAST:event_commaButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
       textField1.setText(textField1.getText() + "0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
       num = Integer.parseInt(textField1.getText());
       perhitungan=4;
       textField1.setText("");
       resultField.setText(num + "/"); 
    }//GEN-LAST:event_divideButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
       textField1.setText(textField1.getText() + "3");
    }//GEN-LAST:event_threeButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        textField1.setText(textField1.getText() + "2");
    }//GEN-LAST:event_twoButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        textField1.setText(textField1.getText() + "1");
    }//GEN-LAST:event_oneButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
          x = Double.valueOf(textField1.getText());
         sin =Math.log10(x);
         textField1.setText(""+sin);
         resultField.setText("Log("+x+")=");
    }//GEN-LAST:event_logButtonActionPerformed

    private void sinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinButtonActionPerformed
        x = Double.valueOf(textField1.getText());
            sin =Math.sin(Math.toRadians(x));
            textField1.setText(""+sin);
            resultField.setText("Sin("+x+")=");
    }//GEN-LAST:event_sinButtonActionPerformed

    private void sinhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhButtonActionPerformed
        x = Double.valueOf(textField1.getText());
            sin =Math.sinh(Math.toRadians(x));
            textField1.setText(""+sin);
            resultField.setText("Sinh("+x+")=");
    }//GEN-LAST:event_sinhButtonActionPerformed

    private void phiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phiButtonActionPerformed
          x = Double.valueOf(textField1.getText());
         sin =x * Math.PI;
         textField1.setText(""+sin);
         resultField.setText("Phi*"+x+"=");
    }//GEN-LAST:event_phiButtonActionPerformed

    private void cosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosButtonActionPerformed
         x = Double.valueOf(textField1.getText());
         sin =Math.cos(Math.toRadians(x));
         textField1.setText(""+sin);
         resultField.setText("Cos("+x+")=");
    }//GEN-LAST:event_cosButtonActionPerformed

    private void coshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshButtonActionPerformed
          x = Double.valueOf(textField1.getText());
            sin =Math.cosh(Math.toRadians(x));
            textField1.setText(""+sin);
            resultField.setText("Cosh("+x+")=");
    }//GEN-LAST:event_coshButtonActionPerformed

    private void xyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyButtonActionPerformed
       
        
    }//GEN-LAST:event_xyButtonActionPerformed

    private void tanButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanButttonActionPerformed
         x = Double.valueOf(textField1.getText());
         sin =Math.tan(x);
         textField1.setText(""+sin);
         resultField.setText("Log("+x+")=");
    }//GEN-LAST:event_tanButttonActionPerformed

    private void tanhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhButtonActionPerformed
          x = Double.valueOf(textField1.getText());
            sin =Math.tanh(Math.toRadians(x));
            textField1.setText(""+sin);
            resultField.setText("Tanh("+x+")=");
    }//GEN-LAST:event_tanhButtonActionPerformed

    private void x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ButtonActionPerformed
        x = Double.valueOf(textField1.getText());
            sin =Math.pow(x, 2);
            textField1.setText(""+sin);
            resultField.setText(x+"^2");
    }//GEN-LAST:event_x2ButtonActionPerformed

    private void cbrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrButtonActionPerformed
           x = Double.valueOf(textField1.getText());
            sin =Math.cbrt(x);
            textField1.setText(""+sin);
            resultField.setText("Cbtr("+x+")=");
    }//GEN-LAST:event_cbrButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runButtonActionPerformed

    private void x3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x3ButtonActionPerformed
          x = Double.valueOf(textField1.getText());
            sin =Math.pow(x, 3);
            textField1.setText(""+sin);
            resultField.setText(x+"^3");
    }//GEN-LAST:event_x3ButtonActionPerformed

    private void bryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bryButtonActionPerformed
         
    }//GEN-LAST:event_bryButtonActionPerformed

    private void hexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hexButtonActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIjavaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIjavaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIjavaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIjavaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIjavaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton bryButton;
    private javax.swing.JButton cbrButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton coshButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton hexButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logButton;
    private javax.swing.JButton minButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton phiButton;
    private javax.swing.JButton plsminButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton resButton;
    private javax.swing.JTextField resultField;
    private javax.swing.JButton rootButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton sinhButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton tanButtton;
    private javax.swing.JButton tanhButton;
    private javax.swing.JTextField textField1;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton x2Button;
    private javax.swing.JButton x3Button;
    private javax.swing.JButton xyButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
